<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ME86Q7D" failures="3" tests="16" name="Surefire test" time="1.385" errors="0" timestamp="2023-01-10T13:51:36 MSK">
  <testcase classname="myTestNgTest.MyFirstTest" name="testDiv" time="0.435">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
at myTestNgTest.MyFirstTest.testDiv(MyFirstTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDiv -->
  <testcase classname="myTestNgTest.MyFirstTest" name="testDif" time="0.01"/>
  <testcase classname="myTestNgTest.MyFirstTest" name="testSum" time="0.015">
    <failure type="java.lang.AssertionError" message="Failed expected [10] but found [9]">
      <![CDATA[java.lang.AssertionError: Failed expected [10] but found [9]
at myTestNgTest.MyFirstTest.testSum(MyFirstTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testSum -->
  <testcase classname="myTestNgTest.MyFirstTest" name="testMul" time="0.005"/>
  <testcase classname="myTestNgTest.TestDataProvider" name="myTest" time="0.02"/>
  <testcase classname="myTestNgTest.TestDataProvider" name="myTest" time="0.005"/>
  <testcase classname="myTestNgTest.TestDataProvider" name="myTest" time="0.005"/>
  <testcase classname="myTestNgTest.TestDataProvider" name="myTest" time="0.005"/>
  <testcase classname="myTestNgTest.TestDataProvider" name="myTest" time="0.01"/>
  <testcase classname="myTestNgTest.TestDataProvider1" name="testCheckUserLog" time="0.01"/>
  <testcase classname="myTestNgTest.TestDataProvider1" name="testCheckUserLog" time="0.005"/>
  <testcase classname="myTestNgTest.TestDataProvider1" name="testCheckUserLog" time="0.0"/>
  <testcase classname="myTestNgTest.TestDataProvider1" name="testCheckUserLog" time="0.005"/>
  <testcase classname="myTestNgTest.TestUser" name="createNewUserTest" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at myTestNgTest.TestUser.createNewUserTest(TestUser.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- createNewUserTest -->
  <testcase classname="myTestNgTest.TestUser" name="checkCreateUser" time="0.0">
    <skipped/>
  </testcase> <!-- checkCreateUser -->
  <testcase classname="myTestNgTest.TestUser" name="test1" time="0.005"/>
</testsuite> <!-- Surefire test -->
